### ISSUE TITLE
The Task "Rebuild source list (brew)" always fails and blocks the task queue

### ISSUE THREAD

**Issue by Albator11** [GetOvert/Overt#30]
Upon opening Overt, the update tasks are automatically started. All tasks work aside from "Rebuild source list (brew)" which always fails for me... and when it fails no other tasks will start unless I cancel one of them, then the rest will finish.

#### Summery:
- the task "Rebuild source list (brew)" always fails
- when a task fails, it appears to block the task queue until something like one of the other tasks gets canceled

**Comment by ThatsJustCheesy** [comment]
Thank you for the bug report!

If you could please provide the output from

```
brew tap-info --json=v1 --installed
```

and, if possible, the logs you get from View → Toggle Developer Tools → Console tab → right-click → Save as…

<img width="375" alt="Screen Shot 2022-12-14 at 11 57 25 PM" src="https://user-images.githubusercontent.com/16456186/207776471-89cbebbe-07f0-4666-9198-86375a632577.png">
<img width="231" alt="Screen Shot 2022-12-15 at 12 00 55 AM" src="https://user-images.githubusercontent.com/16456186/207776608-e800bf67-d26a-4712-a701-f35b6210dd05.png">

that would be very helpful. Feel free to redact any info you consider sensitive.

**Comment by Albator11** [comment]
Alright, I'll get that sent to you this Wednesday.  (sorry I can't get it to you sooner)

**Comment by Albator11** [comment]
Alright, here's the info:
[brew-tap-info.txt](https://github.com/GetOvert/Overt/files/10270788/brew-tap-info.txt)
[overt-tasks.log](https://github.com/GetOvert/Overt/files/10270786/overt-tasks.log)

I forgot that I had a local brew tap `albator/local` that I was messing around with for getting prebuilt binaries like ffmpeg and stuff... it's currently not hosted anyway, so that might be the problem somehow? I untapped it and Overt worked fine... so I guess there's some sort of problem with it.

I think these are probably the important lines in the overt-tasks.log:
```
DevTools failed to load source map: Could not parse content for file:///Applications/Overt.app/Contents/Resources/app/.webpack/renderer/main_window/preload.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///Applications/Overt.app/Contents/Resources/app/.webpack/renderer/main_window/index.js.map: Unexpected end of JSON input
```

**Comment by ThatsJustCheesy** [comment]
Turns out I had incorrectly assumed that taps would always have remote URLs. [Version 0.5.4](https://github.com/GetOvert/Overt/releases/tag/v0.5.4) should resolve both the problems you encountered here. If not, please reopen this, or file a new issue.

Thanks for the help :) and have a wonderful holiday time.

**Comment by Albator11** [comment]
It works perfectly! Thank you!
